### ISSUE TITLE
Your website for other cities

### ISSUE THREAD

**Issue by angoca** [xamanu/mapanica-rutas#1]
Hi,

I've discovered the Mapanica project, and I found this amazing. I am part of a project with similar ideas for the city of Bogota (BogoMap). We have collected the bus stops positions and several routes, and we are publishing all this data in OpenStreetMap.

I would like to know if your web site can be reused, because it does not have any License file in the repository. Beside, I would like like to know it configuring other data set (for the routes) is possible.

Best regards,

**Comment by xamanu** [comment]
Hi @angoca,

of course, please reuse the website! Consider it published under the the WTFPL licence (http://www.wtfpl.net/about/).

Of course we are happy for any push request with improvements you will have. And, of course you can use just the routes' data from another city, this wouldn't be a problem.

Please get in touch with me directly over email and I can also help you with details and share the scripts I use to extract the data from OSM.

Saludos.

**Comment by angoca** [comment]
Hi Felix,

I wrote you a message to what it seems is your email (firstName @ lastname.de). I hope you receive it, if not, please tell me.

Gracias,


Andres

**Comment by xamanu** [comment]
I got it. It's a pleasure to be in contact. Cheers.
