### ISSUE TITLE
License with copyright to Google

### ISSUE THREAD

**Issue by angoca** [xamanu/mapanica-rutas#3]
Hi

I've seen that a license was added to this project, however it is copyrighted to Google and associated with AngularJS, is it normal?

**Comment by xamanu** [comment]
Thanks @angoca for reporting, I just copied over the licence text and I wasn't putting attention to the note on top of it. It is definitively not copyrighted by Google and the MIT license should allow to do almost everything with it. Feel free to do whatever you want with it, no attribution is necessary.
